excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://harshawleigh22.github.io
title: Construction
email: 
author: harshawleigh22
description: My awesome new site
paginate: 3
google_analytics: 